version: '3'

services:
  nginx:
    image: nginx:alpine
    volumes:
      - ../src:/usr/share/nginx/html
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80
